# Generated by Django 3.0 on 2020-05-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pic',
            field=models.ImageField(default='pic/1.png', upload_to='pic'),
        ),
    ]
